// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://doyttekxvonlwmmxfezd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRveXR0ZWt4dm9ubHdtbXhmZXpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyMDg1ODYsImV4cCI6MjA3Nzc4NDU4Nn0.8eCscealjEcOydcAEE-rklpbl1IHp3O47vZ7eTCycSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});